export const TOGGLE_REPLY_MODAL = "SET_REPLY_MODAL";

export const SIGNUP_REQ = "SIGNUP_REQ";
export const SIGNUP_ERR = "SIGNUP_ERR";
export const SIGNUP_SUCC = "SIGNUP_SUCC";

export const LOGIN_SUCC = "LOGIN_SUCC";
export const LOGIN_REQ = "LOGIN_REQ";
export const LOGIN_ERR = "LOGIN_ERR";

export const LOGOUT = "LOGOUT";
export const CLEAR_ALL = "CLEAR_ALL";
export const LOAD_USER = "LOAD_USER";

export const CREATE_POST_REQ = "CREATE_POST_REQ";
export const CREATE_POST_SUCC = "CREATE_POST_SUCC";
export const CREATE_POST_ERR = "CREATE_POST_ERR";

export const DELETE_POST_REQ = "DELETE_POST_REQ";
export const DELETE_POST_SUCC = "DELETE_POST_SUCC";
export const DELETE_POST_ERR = "DELETE_POST_ERR";

export const CREATE_REPLY_REQ = "CREATE_REPLY_REQ";
export const CREATE_REPLY_SUCC = "CREATE_REPLY_SUCC";
export const CREATE_REPLY_ERR = "CREATE_REPLY_ERR";

export const COMMENT_NUMBER_HANDLER = "COMMENT_NUMBER_HANDLER";

export const GET_ALL_POSTS_REQ = "GET_ALL_POSTS_REQ";
export const GET_ALL_POSTS_SUCC = "GET_ALL_POSTS_SUCC";
export const GET_ALL_POSTS_ERR = "GET_ALL_POSTS_ERR";

export const GET_POST_REQ = "GET_POST_REQ";
export const GET_POST_SUCC = "GET_POST_SUCC";
export const GET_POST_ERR = "GET_POST_ERR";

export const LIKE_POST_SUCC = "LIKE_POST_SUCC";
export const LIKE_POST_ERR = "LIKE_POST_ERR";

export const LIKE_POST_SUCC2 = "LIKE_POST_SUCC2";

export const RETWEET_POST_ERR = "RETWEET_POST_ERR";
export const RETWEET_POST_SUCC = "RETWEET_POST_SUCC";
export const RETWEET_POST_SUCC2 = "RETWEET_POST_SUCC2";

export const GET_USER_PROFILE_REQ = "GET_USER_PROFILE_REQ";
export const GET_USER_PROFILE_ERR = "GET_USER_PROFILE_ERR";
export const GET_USER_PROFILE_SUCC = "GET_USER_PROFILE_SUCC";

export const GET_USER_POSTS_SUCC = "GET_USER_POSTS_SUCC";
export const GET_USER_POSTS_ERR = "GET_USER_POSTS_ERR";
export const GET_USER_POSTS_REQ = "GET_USER_POSTS_REQ";
export const CLEAR_USER_POSTS = "CLEAR_USER_POSTS";

export const TOGGLE_FOLLOW_SUCC = "TOGGLE_FOLLOW_SUCC";

export const GET_USERS_BY_KEYWORD_REQ = "GUBKR";
export const GET_USERS_BY_KEYWORD_SUCC = "GUBKS";
export const GET_USERS_BY_KEYWORD_ERR = "GUBKE";

export const GET_USERS_REQ = "GET_USERS_REQ";
export const GET_USERS_ERR = "GET_USERS_ERR";
export const GET_USERS_SUCC = "GET_USERS_SUCC";

export const CREATE_CHAT_REQ = "CREATE_CHAT_REQ";
export const CREATE_CHAT_SUCC = "CREATE_CHAT_SUCC";
export const CREATE_CHAT_ERR = "CREATE_CHAT_ERR";

export const GET_CHATLIST_REQ = "GETMY_CHATLIST_REQ";
export const GET_CHATLIST_ERR = "GETMY_CHATLIST_ERR";
export const GET_CHATLIST_SUCC = "GETMY_CHATLIST_SUCC";

export const GET_CHAT_REQ = "GET_CHAT_REQ";
export const GET_CHAT_SUCC = "GET_CHAT_SUCC";
export const GET_CHAT_ERR = "GET_CHAT_ERR";

export const GET_MESSAGES_REQ = "GET_MESSAGES_REQ";
export const GET_MESSAGES_SUCC = "GET_MESSAGES_SUCC";
export const GET_MESSAGES_ERR = "GET_MESSAGES_ERR";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGE_ERR = "ADD_MESSAGE_ERR";
