export const TOGGLE_REPLY_MODAL = "SET_REPLY_MODAL";

export const SIGNUP_REQ = "SIGNUP_REQ";
export const SIGNUP_ERR = "SIGNUP_ERR";
export const SIGNUP_SUCC = "SIGNUP_SUCC";

export const LOGIN_SUCC = "LOGIN_SUCC";
export const LOGIN_REQ = "LOGIN_REQ";
export const LOGIN_ERR = "LOGIN_ERR";

export const LOGOUT = "LOGOUT";
export const CLEAR_ALL = "CLEAR_ALL";
export const LOAD_USER = "LOAD_USER";

export const CREATE_POST_REQ = "CREATE_POST_REQ";
export const CREATE_POST_SUCC = "CREATE_POST_SUCC";
export const CREATE_POST_ERR = "CREATE_POST_ERR";

export const CREATE_REPLY_REQ = "CREATE_REPLY_REQ";
export const CREATE_REPLY_SUCC = "CREATE_REPLY_SUCC";
export const CREATE_REPLY_ERR = "CREATE_REPLY_ERR";

export const GET_ALL_POSTS_REQ = "GET_ALL_POSTS_REQ";
export const GET_ALL_POSTS_SUCC = "GET_ALL_POSTS_SUCC";
export const GET_ALL_POSTS_ERR = "GET_ALL_POSTS_ERR";

export const GET_POST_REQ = "GET_POST_REQ";
export const GET_POST_SUCC = "GET_POST_SUCC";
export const GET_POST_ERR = "GET_POST_ERR";

export const LIKE_POST_SUCC = "LIKE_POST_SUCC";
export const LIKE_POST_ERR = "LIKE_POST_ERR";

export const LIKE_POST_SUCC2 = "LIKE_POST_SUCC2";

export const RETWEET_POST_ERR = "RETWEET_POST_ERR";
export const RETWEET_POST_SUCC = "RETWEET_POST_SUCC";
export const RETWEET_POST_SUCC2 = "RETWEET_POST_SUCC2";

export const GET_USER_PROFILE_REQ = "GET_USER_PROFILE_REQ";
export const GET_USER_PROFILE_ERR = "GET_USER_PROFILE_ERR";
export const GET_USER_PROFILE_SUCC = "GET_USER_PROFILE_SUCC";

export const GET_USER_POSTS_SUCC = "GET_USER_POSTS_SUCC";
export const GET_USER_POSTS_ERR = "GET_USER_POSTS_ERR";
export const GET_USER_POSTS_REQ = "GET_USER_POSTS_REQ";

export const TOGGLE_FOLLOW_SUCC = "TOGGLE_FOLLOW_SUCC";

export const GET_USERS_BY_KEYWORD_REQ = 'GUBKR'
export const GET_USERS_BY_KEYWORD_SUCC = 'GUBKS'
export const GET_USERS_BY_KEYWORD_ERR = 'GUBKE'
